version: "3.8"

services:
  sentinel:
    build:
      context: .
      dockerfile: sentinel/Dockerfile
    image: sentinel
    container_name: sentinel
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./sentinel/app/logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - 6379:6379
    volumes:
      - cache:/data
    networks:
      - app-net
    depends_on:
      - sentinel

  consumer-worker:
      build:
        context: .
        dockerfile: Dockerfile.worker
      command: ["python", "-m", "worker.consumer"]
      depends_on:
        - redis-server
      networks:
        - app-net
      env_file: .env
      
  clickhouse-writer:
      build:
        context: .
        dockerfile: Dockerfile.worker
      command: ["python", "-m", "worker.clickhouse_writer"]
      depends_on:
        - redis-server
      networks:
        - app-net
      env_file: .env


  # clickhouse:
  #   image: clickhouse:latest
  #   container_name: clickhouse
    

  # vector:
  #   image: timberio/vector:latest-alpine
  #   container_name: vector
  #   volumes:
  #     - ./sentinel/app/logs:/var/log/sentinel:ro
  #     - /usr/local/var/log/suricata:/var/log/suricata:ro
  #     - ./observability:/etc/vector:ro
  #   command: ["--config", "/etc/vector/vector.yaml"]
  #   depends_on:
  #     - sentinel

volumes:
  postgres:
  consumer:
  cache:

networks:
  app-net:
    driver: bridge
